name: CI

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  main:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
