name: Publish

on:
  release:
    types: [created]

jobs:

  npm_release:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lerna Publish
        run: |
          git tag -d ${{ github.event.release.tag_name }}
          lerna version ${{github.event.release.tag_name}} --no-push --yes
          lerna publish from-git --yes
