name: Publish

on:
  release:
    types: [created]

jobs:

  npm_release:
    name: NPM Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lerna Version
        run: npx lerna version ${{github.event.release.tag_name}} --no-push --yes --no-git-tag-version

      - name: Create a commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: release ${{github.event.release.tag_name}}"
          new_branch: master
        continue-on-error: true

      - name: Lerna Publish
        run: npx lerna publish from-package --yes
